<?php
namespace Page\View;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-20 at 09:25:05.
 */
class ViewManagerTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Page\View\ViewManager::setViewClass
     * @todo   Implement testSetViewClass().
     */
    public function testSetViewClass()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Page\View\ViewManager::setViewClasses
     * @todo   Implement testSetViewClasses().
     */
    public function testSetViewClasses()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Page\View\ViewManager::setEditorViewClass
     * @todo   Implement testSetEditorViewClass().
     */
    public function testSetEditorViewClass()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Page\View\ViewManager::setEditorViewClasses
     * @todo   Implement testSetEditorViewClasses().
     */
    public function testSetEditorViewClasses()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Page\View\ViewManager::getView
     * @todo   Implement testGetView().
     */
    public function testGetView()
    {
        $this->assertInstanceOf("Page\View\StringView", ViewManager::getView("hello Rus"), "Представление для типа string создано неправильно");
        $this->assertInstanceOf("Page\View\ExceptionView", ViewManager::getView(new \Page\Exception("one")), "Представление для типа \Page\Exception создано неправильно");
    }

    /**
     * @covers Page\View\ViewManager::getEditorView
     * @todo   Implement testGetEditorView().
     */
    public function testGetEditorView()
    {
        $this->assertInstanceOf("Page\View\EditorStringView", ViewManager::getEditorView("hello Rus"), "Представление для типа строка создано неправильно");
    }
}