<?php
namespace Page;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-10 at 16:22:29.
 */
class MulticastDelegateTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var MulticastDelegate
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new MulticastDelegate;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Page\MulticastDelegate::clear
     * @todo   Implement testClear().
     */
    public function testClear()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
    
    /**
     * @covers Page\MulticastDelegate::add
     * @todo   Implement testAdd().
     */
    public function testAdd()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Page\MulticastDelegate::set
     * @todo   Implement testSet().
     */
    public function testSet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Page\MulticastDelegate::remove
     * @todo   Implement testRemove().
     */
    public function testRemove()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Page\MulticastDelegate::call
     * @todo   Implement testCall().
     */
    public function testCall()
    {
        $arr= new Arr(array(1,2,3));
        $this->object->add(array($arr, "clear"));
        $this->object->call();
        
        $this->assertEquals(0, $arr->count(), "делегат внутри мультикастового делегата не выполняется");

    }
}
